targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/model/entities/*.dart
            - lib/model/entities/**/*.dart
            - lib/model/use_cases/*.dart
            - lib/model/use_cases/**/*.dart
            - lib/results/*.dart